import json
import zipfile
from contextlib import redirect_stdout
from io import StringIO


from laser_test_pattern_generator import app


def run_app(args: list[str]) -> str:
    output = StringIO()

    with redirect_stdout(output):
        exit_code = app.main(args)

    assert exit_code == 0
    return output.getvalue()


def test_generated_nc_file_contains_expected_laser_commands(tmp_path):
    output_path = tmp_path / "validation.nc"

    run_app(
        [
            "--format",
            "NC",
            "--output",
            str(output_path),
            "--overwrite",
            "--rows",
            "2",
            "--cols",
            "2",
            "--speed-min",
            "1000",
            "--speed-max",
            "1200",
            "--power-min",
            "20",
            "--power-max",
            "40",
            "--tile-size",
            "2",
            "--gap",
            "0",
            "--no-labels",
            "--no-auto-position",
            "--grid-x",
            "0",
            "--grid-y",
            "0",
            "--mode",
            "Line",
            "--nc-power-profile",
            "GRBL (0-1000)",
        ]
    )

    assert output_path.exists()
    text = output_path.read_text(encoding="utf-8")

    assert text.strip()
    assert "; Generated by Laser Test Pattern Generator" in text
    assert "G21 ; millimeters" in text
    assert "G90 ; absolute coordinates" in text
    assert "M3 S200" in text
    assert "M3 S400" in text
    assert "F1000" in text
    assert "F1200" in text
    assert text.count("; Tile row=") == 4


def test_generated_nc_stdout_metadata_matches_output_file(tmp_path):
    output_path = tmp_path / "metadata.nc"

    stdout = run_app(
        [
            "--format",
            "NC",
            "--output",
            str(output_path),
            "--overwrite",
            "--rows",
            "2",
            "--cols",
            "3",
            "--speed-min",
            "1000",
            "--speed-max",
            "1200",
            "--power-min",
            "10",
            "--power-max",
            "30",
            "--no-labels",
        ]
    )

    json_text = stdout.split("\n\nFor MKS:", 1)[0]
    metadata = json.loads(json_text)

    assert metadata["output"] == str(output_path)
    assert metadata["format"] == "NC"
    assert metadata["tiles"] == 6
    assert metadata["speeds_visual_top_to_bottom"] == [1200, 1000]
    assert metadata["powers_left_to_right"] == [10, 20, 30]
    assert metadata["lines"] > 0
    assert output_path.exists()
    assert output_path.stat().st_size > 0


def test_generated_mks_file_is_valid_project_zip(tmp_path):
    output_path = tmp_path / "validation.mks"

    run_app(
        [
            "--format",
            "MKS",
            "--output",
            str(output_path),
            "--overwrite",
            "--rows",
            "2",
            "--cols",
            "2",
            "--speed-min",
            "1000",
            "--speed-max",
            "1200",
            "--power-min",
            "20",
            "--power-max",
            "40",
            "--no-labels",
        ]
    )

    assert output_path.exists()
    assert output_path.stat().st_size > 0
    assert zipfile.is_zipfile(output_path)

    with zipfile.ZipFile(output_path) as archive:
        names = set(archive.namelist())
        assert {"makera", "makera.bin", "makera.prj", "prjImg.png"}.issubset(names)

        project = json.loads(archive.read("makera.prj").decode("utf-8"))

    assert "project" in project
    coordinate = project["project"]["lstCoordinate"]["0"]
    assert len(coordinate["path"]) == 4
    assert project["project"]["nGraphihcessMaxNum"] == 4


def test_both_output_creates_mks_and_nc_files(tmp_path):
    output_path = tmp_path / "both_output.mks"

    stdout = run_app(
        [
            "--format",
            "Both",
            "--output",
            str(output_path),
            "--overwrite",
            "--rows",
            "1",
            "--cols",
            "2",
            "--power-min",
            "20",
            "--power-max",
            "40",
            "--no-labels",
        ]
    )

    mks_path = tmp_path / "both_output.mks"
    nc_path = tmp_path / "both_output.nc"

    assert mks_path.exists()
    assert nc_path.exists()
    assert mks_path.stat().st_size > 0
    assert nc_path.stat().st_size > 0

    json_text = stdout.split("\n\nFor MKS:", 1)[0]
    metadata = json.loads(json_text)

    assert isinstance(metadata, list)
    assert len(metadata) == 2

    assert any("paths" in entry for entry in metadata)

    nc_entries = [entry for entry in metadata if entry.get("format") == "NC"]
    assert len(nc_entries) == 1
    assert nc_entries[0]["output"] == str(nc_path)
    assert nc_entries[0]["lines"] > 0
    assert nc_entries[0]["tiles"] == 2
