from __future__ import annotations

import math
from typing import Dict, List, Sequence

from .font import text_segments
from .geometry import apply_auto_position, linspace
from .paths import resolve_output_path
from .settings import APP_VERSION, GeneratorSettings, LASER_MODES, NC_POWER_PROFILES


def power_to_s_value(power_percent: float, s_max: float) -> float:
    """Convert percent power to generic G-code S value."""
    return max(0.0, min(float(s_max), float(power_percent) / 100.0 * float(s_max)))


def resolve_nc_s_max(profile: str, custom_s_max: float) -> float:
    """Return the NC S max for a named profile, or the custom value."""
    profile_s_max = NC_POWER_PROFILES.get(profile)
    if profile_s_max is not None:
        return float(profile_s_max)
    return float(custom_s_max)


def profile_for_nc_s_max(s_max: float) -> str:
    """Infer the closest built-in profile for legacy presets that only store S max."""
    try:
        value = float(s_max)
    except Exception:
        return "Custom"

    for profile, profile_s_max in NC_POWER_PROFILES.items():
        if profile_s_max is not None and math.isclose(value, profile_s_max, rel_tol=0, abs_tol=1e-9):
            return profile
    return "Custom"


def fmt_num(value: float, digits: int = 4) -> str:
    """Compact numeric formatting for G-code."""
    text = f"{float(value):.{digits}f}".rstrip("0").rstrip(".")
    return text if text else "0"


def fmt_s_value(value: float, s_max: float) -> str:
    """Format S values, preserving Makera-style 0.0/1.0 endpoints."""
    if float(s_max) <= 1.0:
        text = fmt_num(value, 3)
        return text if "." in text else text + ".0"
    return fmt_num(value, 3)


def nc_header(settings: GeneratorSettings, speeds: Sequence[float], powers: Sequence[float]) -> List[str]:
    speed_min = min(speeds)
    speed_max = max(speeds)
    power_min = min(powers)
    power_max = max(powers)

    return [
        f"; Generated by Laser Test Pattern Generator {APP_VERSION}",
        "; Generic NC/G-code output. Verify your controller's laser S-value scale before use.",
        f"; NC power profile: {settings.nc_power_profile}",
        f"; NC S max: {fmt_num(settings.nc_s_max, 3)}",
        f"; Power range: {fmt_num(power_min, 6)}% - {fmt_num(power_max, 6)}%",
        f"; Speed range: {fmt_num(speed_min, 6)} - {fmt_num(speed_max, 6)} mm/min",
        f"; Grid: {int(settings.rows)} x {int(settings.cols)}",
        f"; Tile size: {fmt_num(settings.tile_size, 3)} mm",
        f"; Gap: {fmt_num(settings.gap, 3)} mm",
        f"; Mode: {settings.tile_mode_name}",
        f"; Line interval: {fmt_num(settings.line_interval, 3)} mm",
        "G21 ; millimeters",
        "G90 ; absolute coordinates",
        "M5",
    ]


def nc_footer() -> List[str]:
    return [
        "M5",
        "G0 X0 Y0",
        "M2",
    ]


def nc_laser_line(lines: List[str], x1: float, y1: float, x2: float, y2: float, speed: float, power: float, s_max: float) -> None:
    s_value = power_to_s_value(power, s_max)
    lines.append(f"G0 X{fmt_num(x1)} Y{fmt_num(y1)}")
    lines.append(f"M3 S{fmt_s_value(s_value, s_max)}")
    lines.append(f"G1 X{fmt_num(x2)} Y{fmt_num(y2)} F{fmt_num(speed, 1)}")
    lines.append("M5")


def nc_rectangle_outline(lines: List[str], x: float, y: float, w: float, h: float, speed: float, power: float, s_max: float) -> None:
    s_value = power_to_s_value(power, s_max)
    pts = [(x, y), (x+w, y), (x+w, y+h), (x, y+h), (x, y)]
    lines.append(f"G0 X{fmt_num(pts[0][0])} Y{fmt_num(pts[0][1])}")
    lines.append(f"M3 S{fmt_s_value(s_value, s_max)}")
    for px, py in pts[1:]:
        lines.append(f"G1 X{fmt_num(px)} Y{fmt_num(py)} F{fmt_num(speed, 1)}")
    lines.append("M5")


def nc_rectangle_fill(lines: List[str], x: float, y: float, w: float, h: float, speed: float, power: float, s_max: float, interval: float) -> None:
    interval = max(0.01, float(interval))
    count = int(math.floor(h / interval)) + 1
    s_value = power_to_s_value(power, s_max)
    direction = 1
    for i in range(count):
        yy = min(y + i * interval, y + h)
        x_start, x_end = (x, x+w) if direction > 0 else (x+w, x)
        lines.append(f"G0 X{fmt_num(x_start)} Y{fmt_num(yy)}")
        lines.append(f"M3 S{fmt_s_value(s_value, s_max)}")
        lines.append(f"G1 X{fmt_num(x_end)} Y{fmt_num(yy)} F{fmt_num(speed, 1)}")
        lines.append("M5")
        direction *= -1


def nc_rectangle_offset_fill(lines: List[str], x: float, y: float, w: float, h: float, speed: float, power: float, s_max: float, interval: float) -> None:
    interval = max(0.01, float(interval))
    inset = 0.0
    while w - 2*inset > 0.01 and h - 2*inset > 0.01:
        nc_rectangle_outline(lines, x+inset, y+inset, w-2*inset, h-2*inset, speed, power, s_max)
        inset += interval



def generate_generic_nc(settings: GeneratorSettings) -> Dict[str, object]:
    """Generate a generic NC/G-code material test file.

    This is controller-neutral and uses S in range 0..nc_s_max.
    Many laser controllers use different S scales, so users must verify.
    """
    settings.nc_s_max = resolve_nc_s_max(settings.nc_power_profile, settings.nc_s_max)
    rows = int(settings.rows)
    cols = int(settings.cols)

    speeds_raw = linspace(settings.speed_min, settings.speed_max, rows)
    powers_raw = linspace(settings.power_min, settings.power_max, cols)

    speeds = [int(round(v)) for v in speeds_raw] if settings.round_speed_values else [round(v, 6) for v in speeds_raw]
    powers = [int(round(v)) for v in powers_raw] if settings.round_power_values else [round(v, 6) for v in powers_raw]

    if settings.language == "Deutsch":
        power_label = "LEISTUNG (%)"
        speed_label = "GESCHWINDIGKEIT (MM/MIN)"
    else:
        power_label = "POWER (%)"
        speed_label = "SPEED (MM/MIN)"

    tile_mode = LASER_MODES[settings.tile_mode_name]
    grid_w = cols * settings.tile_size + (cols - 1) * settings.gap
    grid_h = rows * settings.tile_size + (rows - 1) * settings.gap
    apply_auto_position(settings, grid_w, grid_h)

    lines = nc_header(settings, speeds, powers)

    # Optional labels: simple stroke lines, not filled bars.
    if settings.labels_enabled and settings.nc_include_labels:
        gx = settings.grid_x
        gy = settings.grid_y

        def add_text_nc(label: str, x: float, y: float, h: float, angle: float = 0.0, anchor: str = "start") -> None:
            for p1, p2 in text_segments(label, x, y, height=h, angle_deg=angle, anchor=anchor):
                nc_laser_line(lines, p1[0], p1[1], p2[0], p2[1], settings.label_speed, settings.label_power, settings.nc_s_max)

        add_text_nc(power_label, gx + grid_w/2, gy + grid_h + 9.5, settings.power_axis_text_height, anchor="middle")
        add_text_nc(speed_label, max(2.5, gx - 16.5), gy + grid_h/2, settings.speed_axis_text_height, angle=-90, anchor="middle")

        for c, power in enumerate(powers):
            cx = gx + c*(settings.tile_size + settings.gap) + settings.tile_size/2
            label = str(int(power)) if isinstance(power, int) or float(power).is_integer() else f"{power:g}"
            add_text_nc(label, cx, gy + grid_h + 3.4, settings.power_number_text_height, anchor="middle")

        for r, speed in enumerate(speeds):
            cy = gy + r*(settings.tile_size + settings.gap) + settings.tile_size/2 - 1.0
            label = str(int(speed)) if isinstance(speed, int) or float(speed).is_integer() else f"{speed:g}"
            add_text_nc(label, gx - 5.0, cy + settings.speed_number_text_height / 2, settings.speed_number_text_height, anchor="end")

    # Tiles
    for r, speed in enumerate(speeds):
        for c, power in enumerate(powers):
            x = settings.grid_x + c*(settings.tile_size + settings.gap)
            y = settings.grid_y + r*(settings.tile_size + settings.gap)
            lines.append(f"; Tile row={r+1} col={c+1} speed={speed} power={power}")
            if tile_mode == 0:
                nc_rectangle_outline(lines, x, y, settings.tile_size, settings.tile_size, speed, power, settings.nc_s_max)
            elif tile_mode == 1:
                nc_rectangle_fill(lines, x, y, settings.tile_size, settings.tile_size, speed, power, settings.nc_s_max, settings.line_interval)
            else:
                nc_rectangle_offset_fill(lines, x, y, settings.tile_size, settings.tile_size, speed, power, settings.nc_s_max, settings.line_interval)

    lines.extend(nc_footer())

    out = resolve_output_path(settings.output_path, settings.overwrite_existing, suffix=".nc", settings=settings)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return {
        "output": str(out),
        "format": "NC",
        "lines": len(lines),
        "tiles": rows * cols,
        "speeds_visual_top_to_bottom": list(reversed(speeds)),
        "powers_left_to_right": powers,
        "power_profile": settings.nc_power_profile,
        "s_max": settings.nc_s_max,
    }

